questions = (
    "What is the largest planet in our solar system?",
    "Who wrote 'To Kill a Mockingbird'?",
    "What is the smallest country in the world?",
    "What is the chemical symbol for gold?",
    "Who painted the Mona Lisa?",
    "What is the capital of Japan?",
    "What is the hardest natural substance on Earth?",
    "Who developed the theory of relativity?",
    "What is the longest river in the world?",
    "What is the capital of Canada?",
    "Who is known as the father of computers?",
    "What is the largest ocean on Earth?",
    "What is the main ingredient in guacamole?",
    "Who was the first person to walk on the moon?",
    "What is the capital of Italy?",
    "What is the tallest mountain in the world?",
    "Who wrote '1984'?",
    "What is the currency of the United Kingdom?",
    "What is the largest desert in the world?",
    "What is the capital of Egypt?"
)

answers = (
    "Jupiter",
    "Harper Lee",
    "Vatican City",
    "Au",
    "Leonardo da Vinci",
    "Tokyo",
    "Diamond",
    "Albert Einstein",
    "Nile",
    "Ottawa",
    "Charles Babbage",
    "Pacific Ocean",
    "Avocado",
    "Neil Armstrong",
    "Rome",
    "Mount Everest",
    "George Orwell",
    "Pound Sterling",
    "Sahara",
    "Cairo"
)